# Generated by Django 4.2.1 on 2023-06-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=50)),
                ('PhoneNumber', models.CharField(max_length=12)),
                ('Gender', models.CharField(max_length=20)),
                ('Address', models.TextField()),
                ('DOB', models.CharField(max_length=20)),
                ('SelectMembershipPlan', models.CharField(max_length=20)),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=190)),
                ('price', models.CharField(max_length=50)),
            ],
        ),
    ]
